<?php

namespace Billetterie\BilletterieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panierRepository extends EntityRepository
{
    public function prochainIDPanier ()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('max(a.id)');

        return $qb  ->getQuery()
            ->getSingleScalarResult();

    }

}
