<?php

namespace Billetterie\BilletterieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * tarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tarifRepository extends EntityRepository
{
    public function RecupTarifBillet ($id)
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('Billetterie\BilletterieBundle\Entity\client', 'c')
            ->addSelect('a')
            ->where('a.id = c.tarif')
            ->andWhere('c.panier = :id')
            ->setParameter('id', $id);

        return $qb  ->getQuery()
                    ->getResult();
    }

}
