<?php

namespace Billetterie\BilletterieBundle\Repository;

use Billetterie\BilletterieBundle\Entity\panier;
use Doctrine\ORM\EntityRepository;

/**
 * clientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientRepository extends EntityRepository
{
    public function recupNbrClient ($panier)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('count(a)')
            ->where('a.panier = :panier')
            ->setParameter('panier', $panier);

        return $qb  ->getQuery()
            ->getSingleScalarResult();

    }

}
