<?php

namespace Billetterie\BilletterieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * tarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tarifRepository extends EntityRepository
{
}
