<?php

namespace Billetterie\BilletterieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function recupNbrClient ($panier)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('count(a)')
            ->where('a.panier = :panier')
            ->setParameter('panier', $panier);

        return $qb  ->getQuery()
            ->getSingleScalarResult();

    }

    public function recupTarifClient ($panier)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.panier = :panier')
            ->setParameter('panier', $panier);

        return $qb  ->getQuery()
                    ->getResult();

    }

    public function recupMontantTotalBillet ($id, $em)
    {
        $clients = $em->getRepository('BilletterieBundle:Client')->findBy(array("panier" => $id));

        $coutTotal = 0;

        foreach ($clients as $client)
        {
            $cout = $client->getTarif()->getMontant();
            $coutTotal += $cout;
        }
        return $coutTotal;
    }

    public function RecupMontantBilletParClient ($id, $em)
    {
        $clients = $em->getRepository('BilletterieBundle:Client')->findBy(array("panier"=>$id));

        return $clients;
    }

    public function RecupClients ($id, $em)
    {
        $clients = $em->getRepository('BilletterieBundle:Client')->findBy(array("panier"=>$id));

        return $clients;
    }

}
